Fixes for redash deployment

diff --git a/docker-config/redash/Dockerfile b/docker-config/redash/Dockerfile
--- a/docker-config/redash/Dockerfile
+++ b/docker-config/redash/Dockerfile
@@ -2,12 +2,10 @@ FROM gliderlabs/alpine:edge
 
 # Packages and dependencies
 RUN apk add --update git libpq python bash sudo
-RUN apk add --update --virtual=build-dependencies python-dev build-base pwgen libffi-dev ca-certificates
-RUN apk add --update --virtual=build-dependencies wget curl tar
-RUN apk add --update --virtual=build-dependencies mariadb-dev postgresql-dev
-RUN apk add --update --virtual=build-dependencies nodejs postgresql
+RUN apk add --no-cache --virtual=build-dependencies \
+    python-dev build-base pwgen libffi-dev ca-certificates \
+    wget curl tar mariadb-dev postgresql-dev nodejs postgresql
 RUN curl -L https://npmjs.org/install.sh | sh
-RUN npm --version
 
 # CA Certificates
 RUN update-ca-certificates
@@ -34,7 +32,8 @@ ENV REDASH_STATIC_ASSETS_PATH="../rd_ui/dist/"
 # Install project specific dependencies
 RUN pip install -r requirements.txt
 RUN PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=yes pip install -r requirements_all_ds.txt
-RUN sudo -u redash -H make deps
+RUN sudo -u redash -H make deps && \
+ rm -rf rd_ui/node_modules /home/redash/.npm /home/redash/.cache
 
 # Setup supervisord
 RUN mkdir -p /opt/redash/supervisord && \
@@ -44,6 +43,7 @@ RUN mkdir -p /opt/redash/supervisord && \
 # Fix permissions
 RUN chown -R redash /opt/redash
 
+# Cleanup
 RUN apk del build-dependencies
 RUN rm -rf /var/cache/apk/*
 
@@ -51,15 +51,14 @@ RUN rm -rf /var/cache/apk/*
 EXPOSE 5000
 EXPOSE 9001
 
-RUN apk add --update nodejs
-
 # Startup script
 CMD  cd /opt/redash/current && touch .env && \
-    (./bin/run python manage.py database create_tables && \
-     ./bin/run python manage.py users grant_admin adam.kariv@okfn.org && \
-     ./bin/run python manage.py ds delete OpenSpending && \
-     ./bin/run python manage.py ds new -n OpenSpending -t pg -o \
-     "{\"user\": \"$DB_USER\", \"host\": \"$DB_HOST\", \"dbname\": \"$DB_NAME\", \"password\": $DB_PWD }") || true && \
+     echo $REDASH_DATABASE_URL && \
+     (./bin/run python manage.py database create_tables || true ) && \
+     (./bin/run python manage.py ds new -n OpenSpending -t pg -o \
+     "{\"user\": \"$OS_DB_USER\", \"host\": \"$OS_DB_HOST\", \"dbname\": \"$OS_DB_NAME\", \"password\": $OS_DB_PWD }") || true && \
+     (./bin/run python manage.py users grant_admin adam.kariv@okfn.org ) || true && \
      /usr/bin/supervisord -c /opt/redash/supervisord/supervisord.conf
-#     && git fetch && git checkout origin/master && \
+# RUN apk add --update nodejs
+# git fetch && git checkout origin/master && \
 #     (cd rd_ui && sudo -u redash node_modules/.bin/gulp ) && \
